worker_processes auto;

error_log /home/container/logs/nginx/error.log;

pid /home/container/logs/nginx/nginx.pid;


events {
    worker_connections 1024;
}


http {

    include mime.types;

    default_type application/octet-stream;


    access_log /home/container/logs/nginx/access.log;


    client_body_temp_path /home/container/tmp/nginx/client_body;
    proxy_temp_path /home/container/tmp/nginx/proxy;
    fastcgi_temp_path /home/container/tmp/nginx/fastcgi;


    sendfile on;


    include conf.d/*.conf;

}
